server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

#编辑dubbo配置
dubbo:
  scan:
    base-packages: com.jl
  application:
    name: consumer-web
  registry:
    address: zookeeper://192.168.56.129:2181?backup=192.168.56.129:2182,192.168.56.129:2183